apiVersion: v1
kind: ConfigMap
metadata:
  name: psa-master-cm
  namespace: cctns-new
data:
  master_server_address: psa-master-svc.cctns-new.svc.cluster.local
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: master-app
  name: psa-master-server-app
  namespace: cctns-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-app
  template:
    metadata:
      labels:
        app: master-app
    spec:
      containers:
      - env:
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: config_server_address
              name: psa-config-cm
        - name: MASTER_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: master_server_address
              name: psa-master-cm
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_server_address
              name: psa-eureka-cm
        - name: APPLICATION_SERVER
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              key: ACTIVE_PROFILE
              name: active-profile
        - name: TZ
          value: Asia/Kolkata
        image: docker-registry:5000/psa-master-server:v1-20
        imagePullPolicy: Always
        name: master-app
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /root/logs
          name: logs-volume
      serviceAccount: cctns
      serviceAccountName: cctns
      volumes:
      - hostPath:
          path: /Data_NAS_NEW/microservice-log/master
          type: ""
        name: logs-volume
---
apiVersion: v1
kind: Service
metadata:
  name: psa-master-svc
  namespace: cctns-new
spec:
  ports:
  - name: http
    nodePort: 31004
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: master-app
  type: NodePort
