apiVersion: v1
kind: ConfigMap
metadata:
  name: psa-identity-data-cm
  namespace: cctns-new
data:
  identity-data_server_address: psa-identity-data-svc.cctns-new.svc.cluster.local

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: identity-data-app
  name: psa-identity-data-server-app
  namespace: cctns-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-data-app
  template:
    metadata:
      labels:
        app: identity-data-app
    spec:
      containers:
      - env:
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: config_server_address
              name: psa-config-cm
        - name: IDENTITY_DATA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: identity-data_server_address
              name: psa-identity-data-cm
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_server_address
              name: psa-eureka-cm
        - name: APPLICATION_SERVER
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              key: ACTIVE_PROFILE
              name: active-profile
        - name: TZ
          value: Asia/Kolkata
        image: docker-registry:5000/psa-identity-data-server:v1-7
        imagePullPolicy: Always
        name: identity-data-app
        ports:
        - containerPort: 9696
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /root/logs
          name: logs-volume
      serviceAccount: cctns
      serviceAccountName: cctns
      volumes:
      - hostPath:
          path: /Data_NAS_NEW/microservice-log/identity
          type: ""
        name: logs-volume
---

apiVersion: v1
kind: Service
metadata:
  name: psa-identity-data-svc
  namespace: cctns-new
spec:
  ports:
  - name: http
    nodePort: 31011
    port: 9696
    protocol: TCP
    targetPort: 9696
  selector:
    app: identity-data-app
  type: NodePort
