apiVersion: v1
kind: ConfigMap
metadata:
  name: psa-gateway-cm
  namespace: cctns-new
data:
  gateway_server_address: 192.168.57.33
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-app
  name: psa-gateway-server-app
  namespace: cctns-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
      - env:
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: config_server_address
              name: psa-config-cm
        - name: GATEWAY_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: gateway_server_address
              name: psa-gateway-cm
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_server_address
              name: psa-eureka-cm
        - name: APPLICATION_SERVER
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: server_address
              name: psa-gateway-cm
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: server_port
              name: psa-gateway-cm
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              key: ACTIVE_PROFILE
              name: active-profile
        - name: TZ
          value: Asia/Kolkata
        image: docker-registry:5000/psa-gateway-server:v1
        imagePullPolicy: Always
        name: gateway-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /root/logs
          name: logs-volume
      serviceAccount: cctns
      serviceAccountName: cctns
      volumes:
      - hostPath:
          path: /Data_NAS_NEW/microservice-log/gateway/
          type: ""
        name: logs-volume
---
apiVersion: v1
kind: Service
metadata:
  name: psa-gateway-svc
  namespace: cctns-new
spec:
  ports:
  - name: http
    nodePort: 31002
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gateway-app
  type: NodePort