apiVersion: v1
data:
  lost-article_server_address: psa-lost-article-svc.cctns-new.svc.cluster.local
kind: ConfigMap
metadata:
  name: psa-lost-article-cm
  namespace: cctns-new
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lost-article-app
  name: psa-lost-article-server-app
  namespace: cctns-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lost-article-app
  template:
    metadata:
      labels:
        app: lost-article-app
    spec:
      containers:
      - env:
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: config_server_address
              name: psa-config-cm
        - name: LOST_ARTICLE_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: lost-article_server_address
              name: psa-lost-article-cm
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_server_address
              name: psa-eureka-cm
        - name: APPLICATION_SERVER
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              key: ACTIVE_PROFILE
              name: active-profile
        - name: TZ
          value: Asia/Kolkata
        image: docker-registry:5000/psa-lost-article-server:v1
        imagePullPolicy: Always
        name: lost-article-app
        ports:
        - containerPort: 8087
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/logs
          name: logs-volume
      serviceAccount: cctns
      serviceAccountName: cctns
      volumes:
      - hostPath:
          path: /Data_NAS_NEW/microservice-log/lost-service
          type: ""
        name: logs-volume
---
apiVersion: v1
kind: Service
metadata:
  name: psa-lost-article-svc
  namespace: cctns-new
spec:
  ports:
  - name: http
    nodePort: 31006
    port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: lost-article-app
  type: NodePort
