apiVersion: v1
kind: ConfigMap
metadata:
  name: psa-react-cm
  namespace: cctns-new
data:
  react_server_address: psa-react-portal-svc.cctns-new.svc.cluster.local  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psa-react-portal-app
  namespace: cctns-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-portal
  template:
    metadata:
      labels:
        app: react-portal
    spec:
      containers:
      - env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_server_address
              name: psa-eureka-cm
        - name: CONFIG_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: config_server_address
              name: psa-config-cm
        - name: REACT_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: react_server_address
              name: psa-react-cm
        - name: APPLICATION_SERVER
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: docker-registry:5000/psa-react-portal:v1-23
        imagePullPolicy: Always
        name: react-portal
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccount: cctns
      serviceAccountName: cctns
---
apiVersion: v1
kind: Service
metadata:
  name: psa-react-portal-svc
  namespace: cctns-new
spec:
  ports:
  - nodePort: 31007
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react-portal
  type: NodePort
